name: Run React Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instala dependências
        run: npm install

      - name: Roda os testes
        id: rodar_testes
        run: |
          set -e
          npm test -- --watchAll=false

      - name: Enviar resultado para Discord (Sucesso)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"✅ Testes passaram com sucesso na PR #${{ github.event.pull_request.number }} por ${{ github.event.pull_request.user.login }}.\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Enviar resultado para Discord (Falha)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"❌ Testes falharam na PR #${{ github.event.pull_request.number }} por ${{ github.event.pull_request.user.login }}.\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

